### ISSUE TITLE
Are you planning to implement authentication with client credentials?

### ISSUE THREAD

**Issue by marcelpogorzelski** [bweber226/jps-api-wrapper#1]
Version 10.49 introduced API Roles and Clients. Are you planning to implement this authentication method?

**Comment by bweber226** [comment]
I am planning on having API client auth implemented for the JPS 10.50 release of the jps-api-wrapper or sooner. I will update you as soon as it's implemented.

**Comment by bweber226** [comment]
Just wanted to update you that the latest 1.9.0 release includes API client authentication as an option. I've updated the README on how you can use those to authenticate now. I was waiting to release it since there is a ticket I have in with Jamf related to token refresh with API clients but I've added a workaround that works for the time being into 1.9.0.

**Comment by bweber226** [comment]
Resolved
